-- Claves, unicidad, comprobaciones y relaciones
-- ═══════════════════════════════════════════════════════════════════════════
-- Generado por herramientas/volcar-esquema.sql. NO se edita a mano: se
-- vuelve a generar y se perdería lo escrito. Los cambios se hacen en la
-- base y luego se regenera esto.

alter table public.cem_announcements add constraint cem_announcements_pkey PRIMARY KEY (id);
alter table public.cem_aportes add constraint cem_aportes_pkey PRIMARY KEY (id);
alter table public.cem_appeals add constraint cem_appeals_pkey PRIMARY KEY (id);
alter table public.cem_assessment_questions add constraint cem_assessment_questions_pkey PRIMARY KEY (id);
alter table public.cem_assessments add constraint cem_assessments_pkey PRIMARY KEY (id);
alter table public.cem_attendance add constraint cem_attendance_pkey PRIMARY KEY (id);
alter table public.cem_audit_events add constraint cem_audit_events_pkey PRIMARY KEY (id);
alter table public.cem_badge_awards add constraint cem_badge_awards_pkey PRIMARY KEY (id);
alter table public.cem_badges add constraint cem_badges_pkey PRIMARY KEY (id);
alter table public.cem_bancaribe_notificaciones add constraint cem_bancaribe_notificaciones_pkey PRIMARY KEY (id);
alter table public.cem_bot_borradores add constraint cem_bot_borradores_pkey PRIMARY KEY (id);
alter table public.cem_bot_conocimiento add constraint cem_bot_conocimiento_pkey PRIMARY KEY (id);
alter table public.cem_bot_conversaciones add constraint cem_bot_conversaciones_pkey PRIMARY KEY (id);
alter table public.cem_bot_escuchado add constraint cem_bot_escuchado_pkey PRIMARY KEY (id);
alter table public.cem_bot_mensajes add constraint cem_bot_mensajes_pkey PRIMARY KEY (id);
alter table public.cem_bot_numeros add constraint cem_bot_numeros_pkey PRIMARY KEY (telefono);
alter table public.cem_bot_recordatorios add constraint cem_bot_recordatorios_pkey PRIMARY KEY (profile_id);
alter table public.cem_carteras add constraint cem_carteras_pkey PRIMARY KEY (id);
alter table public.cem_categorias add constraint cem_categorias_pkey PRIMARY KEY (id);
alter table public.cem_certificate_templates add constraint cem_certificate_templates_pkey PRIMARY KEY (id);
alter table public.cem_certificates add constraint cem_certificates_pkey PRIMARY KEY (id);
alter table public.cem_classes add constraint cem_classes_pkey PRIMARY KEY (id);
alter table public.cem_clave_pendiente add constraint cem_clave_pendiente_pkey PRIMARY KEY (profile_id);
alter table public.cem_cohorts add constraint cem_cohorts_pkey PRIMARY KEY (id);
alter table public.cem_comentarios_guardados add constraint cem_comentarios_guardados_pkey PRIMARY KEY (id);
alter table public.cem_compras_invitado add constraint cem_compras_invitado_pkey PRIMARY KEY (id);
alter table public.cem_content_reviews add constraint cem_content_reviews_pkey PRIMARY KEY (id);
alter table public.cem_conversiones add constraint cem_conversiones_pkey PRIMARY KEY (id);
alter table public.cem_correo_cola add constraint cem_correo_cola_pkey PRIMARY KEY (id);
alter table public.cem_course_shorts add constraint cem_course_shorts_pkey PRIMARY KEY (id);
alter table public.cem_courses add constraint cem_courses_pkey PRIMARY KEY (id);
alter table public.cem_datos_de_prueba add constraint cem_datos_de_prueba_pkey PRIMARY KEY (tabla, fila_id);
alter table public.cem_duda_respuestas add constraint cem_duda_respuestas_pkey PRIMARY KEY (id);
alter table public.cem_dudas add constraint cem_dudas_pkey PRIMARY KEY (id);
alter table public.cem_enrollments add constraint cem_enrollments_pkey PRIMARY KEY (id);
alter table public.cem_gastos add constraint cem_gastos_pkey PRIMARY KEY (id);
alter table public.cem_identidad add constraint cem_identidad_pkey PRIMARY KEY (profile_id);
alter table public.cem_installments add constraint cem_installments_pkey PRIMARY KEY (id);
alter table public.cem_integraciones add constraint cem_integraciones_pkey PRIMARY KEY (id);
alter table public.cem_inversores add constraint cem_inversores_pkey PRIMARY KEY (id);
alter table public.cem_invitaciones add constraint cem_invitaciones_pkey PRIMARY KEY (id);
alter table public.cem_invitaciones_equipo add constraint cem_invitaciones_equipo_pkey PRIMARY KEY (id);
alter table public.cem_lead_envios add constraint cem_lead_envios_pkey PRIMARY KEY (id);
alter table public.cem_leads add constraint cem_leads_pkey PRIMARY KEY (id);
alter table public.cem_leccion_valoraciones add constraint cem_leccion_valoraciones_pkey PRIMARY KEY (id);
alter table public.cem_lesson_progress add constraint cem_lesson_progress_pkey PRIMARY KEY (id);
alter table public.cem_lessons add constraint cem_lessons_pkey PRIMARY KEY (id);
alter table public.cem_liquidaciones add constraint cem_liquidaciones_pkey PRIMARY KEY (id);
alter table public.cem_media add constraint cem_media_pkey PRIMARY KEY (id);
alter table public.cem_mensajes_plantilla add constraint cem_mensajes_plantilla_pkey PRIMARY KEY (id);
alter table public.cem_metodos_pago add constraint cem_metodos_pago_pkey PRIMARY KEY (metodo);
alter table public.cem_modules add constraint cem_modules_pkey PRIMARY KEY (id);
alter table public.cem_muro add constraint cem_muro_pkey PRIMARY KEY (id);
alter table public.cem_muro_comentarios add constraint cem_muro_comentarios_pkey PRIMARY KEY (id);
alter table public.cem_notificaciones add constraint cem_notificaciones_pkey PRIMARY KEY (id);
alter table public.cem_payments add constraint cem_payments_pkey PRIMARY KEY (id);
alter table public.cem_permissions add constraint cem_permissions_pkey PRIMARY KEY (id);
alter table public.cem_plantillas_mensaje add constraint cem_plantillas_mensaje_pkey PRIMARY KEY (id);
alter table public.cem_portafolio add constraint cem_portafolio_pkey PRIMARY KEY (id);
alter table public.cem_profiles add constraint cem_profiles_pkey PRIMARY KEY (id);
alter table public.cem_puente_estado add constraint cem_puente_estado_pkey PRIMARY KEY (id);
alter table public.cem_questions add constraint cem_questions_pkey PRIMARY KEY (id);
alter table public.cem_rate_limit add constraint cem_rate_limit_pkey PRIMARY KEY (clave);
alter table public.cem_recurso_entregas add constraint cem_recurso_entregas_pkey PRIMARY KEY (id);
alter table public.cem_recursos add constraint cem_recursos_pkey PRIMARY KEY (id);
alter table public.cem_reproducciones add constraint cem_reproducciones_pkey PRIMARY KEY (id);
alter table public.cem_ronda_partes add constraint cem_ronda_partes_pkey PRIMARY KEY (id);
alter table public.cem_rondas add constraint cem_rondas_pkey PRIMARY KEY (id);
alter table public.cem_settings add constraint cem_settings_pkey PRIMARY KEY (clave);
alter table public.cem_solicitudes_inscripcion add constraint cem_solicitudes_inscripcion_pkey PRIMARY KEY (id);
alter table public.cem_solicitudes_perfil add constraint cem_solicitudes_perfil_pkey PRIMARY KEY (id);
alter table public.cem_stripe_sesiones add constraint cem_stripe_sesiones_pkey PRIMARY KEY (id);
alter table public.cem_submissions add constraint cem_submissions_pkey PRIMARY KEY (id);
alter table public.cem_tasa_peticiones add constraint cem_tasa_peticiones_pkey PRIMARY KEY (id);
alter table public.cem_tasas_bcv add constraint cem_tasas_bcv_pkey PRIMARY KEY (id);
alter table public.cem_teacher_assignments add constraint cem_teacher_assignments_pkey PRIMARY KEY (id);
alter table public.cem_ticket_messages add constraint cem_ticket_messages_pkey PRIMARY KEY (id);
alter table public.cem_tickets add constraint cem_tickets_pkey PRIMARY KEY (id);
alter table public.cem_turnos add constraint cem_turnos_pkey PRIMARY KEY (id);
alter table public.cem_valoraciones add constraint cem_valoraciones_pkey PRIMARY KEY (id);
alter table public.cem_wa_salientes add constraint cem_wa_salientes_pkey PRIMARY KEY (id);
alter table public.cert_carpetas add constraint cert_carpetas_pkey PRIMARY KEY (ruta);
alter table public.cert_certificates add constraint cert_certificates_pkey PRIMARY KEY (id);
alter table public.cert_lotes add constraint cert_lotes_pkey PRIMARY KEY (id);
alter table public.cert_settings add constraint cert_settings_pkey PRIMARY KEY (id);
alter table public.cert_templates add constraint cert_templates_pkey PRIMARY KEY (id);
alter table public.forest_ai_predictions add constraint forest_ai_predictions_pkey PRIMARY KEY (id);
alter table public.forest_audit_events add constraint forest_audit_events_pkey PRIMARY KEY (id);
alter table public.forest_code_sequences add constraint forest_code_sequences_pkey PRIMARY KEY (project_id, anio);
alter table public.forest_profiles add constraint forest_profiles_pkey PRIMARY KEY (id);
alter table public.forest_projects add constraint forest_projects_pkey PRIMARY KEY (id);
alter table public.forest_public_content add constraint forest_public_content_pkey PRIMARY KEY (tree_id);
alter table public.forest_public_templates add constraint forest_public_templates_pkey PRIMARY KEY (ambito);
alter table public.forest_push_subscriptions add constraint forest_push_subscriptions_pkey PRIMARY KEY (id);
alter table public.forest_qr_batches add constraint forest_qr_batches_pkey PRIMARY KEY (id);
alter table public.forest_qr_counter add constraint forest_qr_counter_pkey PRIMARY KEY (id);
alter table public.forest_qr_tags add constraint forest_qr_tags_pkey PRIMARY KEY (id);
alter table public.forest_reviews add constraint forest_reviews_pkey PRIMARY KEY (id);
alter table public.forest_secrets add constraint forest_secrets_pkey PRIMARY KEY (key);
alter table public.forest_species_catalog add constraint forest_species_catalog_pkey PRIMARY KEY (id);
alter table public.forest_species_requests add constraint forest_species_requests_pkey PRIMARY KEY (id);
alter table public.forest_tree_photos add constraint forest_tree_photos_pkey PRIMARY KEY (id);
alter table public.forest_trees add constraint forest_trees_pkey PRIMARY KEY (id);
alter table public.pm_project_events add constraint pm_project_events_pkey PRIMARY KEY (id);
alter table public.pm_projects add constraint pm_projects_pkey PRIMARY KEY (id);
alter table public.quote_events add constraint quote_events_pkey PRIMARY KEY (id);
alter table public.quotes add constraint quotes_pkey PRIMARY KEY (id);
alter table public.cem_assessment_questions add constraint cem_assessment_questions_assessment_id_question_id_key UNIQUE (assessment_id, question_id);
alter table public.cem_attendance add constraint cem_attendance_class_id_enrollment_id_key UNIQUE (class_id, enrollment_id);
alter table public.cem_badge_awards add constraint cem_badge_awards_badge_id_profile_id_key UNIQUE (badge_id, profile_id);
alter table public.cem_bot_conocimiento add constraint cem_bot_conocimiento_clave_key UNIQUE (clave);
alter table public.cem_categorias add constraint cem_categorias_nombre_key UNIQUE (nombre);
alter table public.cem_certificates add constraint cem_certificates_codigo_key UNIQUE (codigo);
alter table public.cem_compras_invitado add constraint cem_compras_invitado_session_id_key UNIQUE (session_id);
alter table public.cem_course_shorts add constraint cem_course_shorts_course_id_video_id_key UNIQUE (course_id, video_id);
alter table public.cem_courses add constraint cem_courses_codigo_key UNIQUE (codigo);
alter table public.cem_invitaciones_equipo add constraint cem_invitaciones_equipo_token_key UNIQUE (token);
alter table public.cem_leccion_valoraciones add constraint cem_leccion_valoraciones_lesson_id_profile_id_key UNIQUE (lesson_id, profile_id);
alter table public.cem_lesson_progress add constraint cem_lesson_progress_enrollment_id_lesson_id_key UNIQUE (enrollment_id, lesson_id);
alter table public.cem_mensajes_plantilla add constraint cem_mensajes_plantilla_clave_key UNIQUE (clave);
alter table public.cem_permissions add constraint cem_permissions_rol_modulo_accion_key UNIQUE (rol, modulo, accion);
alter table public.cem_recursos add constraint cem_recursos_codigo_key UNIQUE (codigo);
alter table public.cem_ronda_partes add constraint cem_ronda_partes_ronda_id_inversor_id_linea_key UNIQUE (ronda_id, inversor_id, linea);
alter table public.cem_stripe_sesiones add constraint cem_stripe_sesiones_session_id_key UNIQUE (session_id);
alter table public.cem_tickets add constraint cem_tickets_codigo_key UNIQUE (codigo);
alter table public.cem_turnos add constraint cem_turnos_nombre_key UNIQUE (nombre);
alter table public.cem_valoraciones add constraint cem_valoraciones_class_id_profile_id_key UNIQUE (class_id, profile_id);
alter table public.forest_push_subscriptions add constraint forest_push_subscriptions_endpoint_key UNIQUE (endpoint);
alter table public.forest_qr_tags add constraint forest_qr_tags_numero_key UNIQUE (numero);
alter table public.forest_qr_tags add constraint forest_qr_tags_token_key UNIQUE (token);
alter table public.forest_trees add constraint forest_trees_codigo_visible_key UNIQUE (codigo_visible);
alter table public.cem_aportes add constraint cem_aportes_concepto_check CHECK ((length(btrim(concepto)) > 0));
alter table public.cem_aportes add constraint cem_aportes_duenio CHECK ((((tipo_capital = 'nuevo'::text) AND (inversor_id IS NOT NULL)) OR ((tipo_capital = 'reinversion'::text) AND (inversor_id IS NULL))));
alter table public.cem_aportes add constraint cem_aportes_monto_base_check CHECK ((monto_base > (0)::numeric));
alter table public.cem_aportes add constraint cem_aportes_monto_check CHECK ((monto > (0)::numeric));
alter table public.cem_aportes add constraint cem_aportes_tasa CHECK (((moneda = 'EUR'::text) OR (tasa IS NOT NULL)));
alter table public.cem_aportes add constraint cem_aportes_tipo_capital_check CHECK ((tipo_capital = ANY (ARRAY['nuevo'::text, 'reinversion'::text])));
alter table public.cem_bot_borradores add constraint cem_bot_borradores_estado_check CHECK ((estado = ANY (ARRAY['pendiente'::text, 'confirmado'::text, 'descartado'::text, 'caducado'::text])));
alter table public.cem_bot_borradores add constraint cem_bot_borradores_tipo_check CHECK ((tipo = ANY (ARRAY['recordatorio_entrega'::text, 'recordatorio_cuota'::text, 'certificados_lote'::text])));
alter table public.cem_bot_conocimiento add constraint cem_bot_conocimiento_ambito_check CHECK ((ambito = ANY (ARRAY['estudiante'::text, 'equipo'::text, 'ambos'::text])));
alter table public.cem_bot_conocimiento add constraint cem_bot_conocimiento_origen_check CHECK ((origen = ANY (ARRAY['manual'::text, 'plataforma'::text])));
alter table public.cem_bot_conversaciones add constraint cem_bot_conversaciones_ambito_check CHECK ((ambito = ANY (ARRAY['estudiante'::text, 'equipo'::text])));
alter table public.cem_bot_conversaciones add constraint cem_bot_conversaciones_canal_check CHECK ((canal = ANY (ARRAY['web'::text, 'whatsapp'::text])));
alter table public.cem_bot_mensajes add constraint cem_bot_mensajes_quien_check CHECK ((quien = ANY (ARRAY['persona'::text, 'asistente'::text, 'equipo'::text])));
alter table public.cem_bot_numeros add constraint cem_bot_numeros_ambito_check CHECK ((ambito = ANY (ARRAY['estudiante'::text, 'equipo'::text])));
alter table public.cem_bot_recordatorios add constraint cem_bot_recordatorios_dias_antes_check CHECK (((dias_antes >= 1) AND (dias_antes <= 30)));
alter table public.cem_carteras add constraint cem_cartera_moneda_valida CHECK ((moneda = ANY (ARRAY['EUR'::text, 'USD'::text, 'VES'::text])));
alter table public.cem_compras_invitado add constraint cem_compras_invitado_cuotas_check CHECK ((cuotas = ANY (ARRAY[1, 3, 6])));
alter table public.cem_compras_invitado add constraint cem_compras_invitado_estado_check CHECK ((estado = ANY (ARRAY['abierta'::text, 'pagada'::text, 'cancelada'::text, 'fallida'::text])));
alter table public.cem_conversiones add constraint cem_conversion_estado_valido CHECK ((estado = ANY (ARRAY['completada'::text, 'pendiente'::text])));
alter table public.cem_conversiones add constraint cem_conversion_tiene_patas CHECK ((((cartera_origen IS NOT NULL) AND (cartera_destino IS NOT NULL) AND (monto_origen > (0)::numeric) AND (monto_destino > (0)::numeric)) OR ((cartera_origen IS NULL) AND (cartera_destino IS NOT NULL) AND (monto_destino <> (0)::numeric))));
alter table public.cem_correo_cola add constraint cem_correo_cola_estado_check CHECK ((estado = ANY (ARRAY['pendiente'::text, 'enviando'::text, 'enviado'::text, 'fallido'::text, 'descartado'::text])));
alter table public.cem_courses add constraint cem_courses_peso_evaluaciones_check CHECK (((peso_evaluaciones >= (0)::numeric) AND (peso_evaluaciones <= (100)::numeric)));
alter table public.cem_gastos add constraint cem_gasto_moneda_valida CHECK ((moneda = ANY (ARRAY['EUR'::text, 'USD'::text, 'VES'::text])));
alter table public.cem_gastos add constraint cem_gastos_linea_o_reparto CHECK (((linea IS NULL) OR (reparto IS NULL)));
alter table public.cem_gastos add constraint cem_gastos_monto_check CHECK ((monto > (0)::numeric));
alter table public.cem_gastos add constraint cem_gastos_reparto_valido CHECK (cem_reparto_valido(reparto));
alter table public.cem_identidad add constraint cem_identidad_estado_check CHECK ((estado = ANY (ARRAY['pendiente'::text, 'aprobado'::text, 'rechazado'::text])));
alter table public.cem_inversores add constraint cem_inversores_color_check CHECK ((color ~ '^#[0-9a-fA-F]{6}$'::text));
alter table public.cem_inversores add constraint cem_inversores_nombre_check CHECK ((length(btrim(nombre)) > 0));
alter table public.cem_invitaciones add constraint cem_invitaciones_cuotas_ok CHECK ((cuotas = ANY (ARRAY[1, 3, 6])));
alter table public.cem_invitaciones add constraint cem_invitaciones_estado_ok CHECK ((estado = ANY (ARRAY['pendiente'::text, 'aceptada'::text, 'rechazada'::text, 'retirada'::text])));
alter table public.cem_leads add constraint cem_leads_algo_para_contactar CHECK ((COALESCE(NULLIF(TRIM(BOTH FROM email), ''::text), NULLIF(TRIM(BOTH FROM telefono), ''::text)) IS NOT NULL));
alter table public.cem_leads add constraint cem_leads_estado_check CHECK ((estado = ANY (ARRAY['nuevo'::text, 'contactado'::text, 'interesado'::text, 'inscrito'::text, 'descartado'::text])));
alter table public.cem_leccion_valoraciones add constraint cem_leccion_valoraciones_util_check CHECK (((util >= 1) AND (util <= 5)));
alter table public.cem_liquidaciones add constraint cem_liquidaciones_monto_base_check CHECK ((monto_base > (0)::numeric));
alter table public.cem_liquidaciones add constraint cem_liquidaciones_monto_check CHECK ((monto > (0)::numeric));
alter table public.cem_liquidaciones add constraint cem_liquidaciones_tasa CHECK (((moneda = 'EUR'::text) OR (tasa IS NOT NULL)));
alter table public.cem_mensajes_plantilla add constraint cem_mensajes_plantilla_tipo_check CHECK ((tipo = ANY (ARRAY['primer-contacto'::text, 'promocion'::text, 'seguimiento'::text, 'recuperacion'::text, 'otro'::text])));
alter table public.cem_metodos_pago add constraint cem_metodo_moneda_valida CHECK ((moneda = ANY (ARRAY['EUR'::text, 'USD'::text, 'VES'::text])));
alter table public.cem_metodos_pago add constraint cem_metodo_regla_valida CHECK ((regla = ANY (ARRAY['uno_a_uno'::text, 'tasa_bcv'::text, 'directo'::text])));
alter table public.cem_puente_estado add constraint cem_puente_estado_una_fila CHECK (id);
alter table public.cem_recursos add constraint cem_recurso_completo CHECK (
CASE tipo
    WHEN 'documento'::text THEN (storage_path IS NOT NULL)
    WHEN 'video'::text THEN (video_id IS NOT NULL)
    WHEN 'enlace'::text THEN (url IS NOT NULL)
    ELSE NULL::boolean
END);
alter table public.cem_recursos add constraint cem_recursos_codigo_check CHECK ((codigo ~ '^[a-z0-9][a-z0-9-]{1,58}[a-z0-9]$'::text));
alter table public.cem_recursos add constraint cem_recursos_tipo_check CHECK ((tipo = ANY (ARRAY['documento'::text, 'video'::text, 'enlace'::text])));
alter table public.cem_recursos add constraint cem_recursos_titulo_check CHECK ((length(btrim(titulo)) > 0));
alter table public.cem_ronda_partes add constraint cem_ronda_partes_aporte_check CHECK ((aporte >= (0)::numeric));
alter table public.cem_ronda_partes add constraint cem_ronda_partes_pct_check CHECK (((pct >= (0)::numeric) AND (pct <= (100)::numeric)));
alter table public.cem_rondas add constraint cem_rondas_nombre_check CHECK ((length(btrim(nombre)) > 0));
alter table public.cem_rondas add constraint cem_rondas_orden CHECK (((hasta IS NULL) OR (hasta >= desde)));
alter table public.cem_solicitudes_inscripcion add constraint cem_solicitudes_inscripcion_estado_check CHECK ((estado = ANY (ARRAY['pendiente'::text, 'aprobada'::text, 'rechazada'::text])));
alter table public.cem_solicitudes_inscripcion add constraint cem_solicitudes_inscripcion_tipo_check CHECK ((tipo = ANY (ARRAY['congelamiento'::text, 'retiro'::text, 'reactivacion'::text, 'plan_de_pago'::text])));
alter table public.cem_solicitudes_perfil add constraint cem_solicitudes_perfil_estado_check CHECK ((estado = ANY (ARRAY['pendiente'::text, 'aprobada'::text, 'rechazada'::text])));
alter table public.cem_tasa_peticiones add constraint cem_tasa_peticiones_estado_ok CHECK ((estado = ANY (ARRAY['pidiendo'::text, 'ok'::text, 'fallo'::text])));
alter table public.cem_tasas_bcv add constraint cem_tasas_moneda_valida CHECK ((moneda = ANY (ARRAY['USD'::text, 'EUR'::text])));
alter table public.cem_valoraciones add constraint cem_valoraciones_claridad_check CHECK (((claridad >= 1) AND (claridad <= 5)));
alter table public.cem_valoraciones add constraint cem_valoraciones_ritmo_check CHECK (((ritmo >= 1) AND (ritmo <= 5)));
alter table public.cem_valoraciones add constraint cem_valoraciones_utilidad_check CHECK (((utilidad >= 1) AND (utilidad <= 5)));
alter table public.cert_certificates add constraint cert_certificates_estado_check CHECK ((estado = ANY (ARRAY['vigente'::text, 'revocado'::text, 'reemplazado'::text])));
alter table public.cert_settings add constraint cert_settings_singleton CHECK ((id = 1));
alter table public.forest_qr_batches add constraint forest_qr_batches_cantidad_check CHECK (((cantidad > 0) AND (cantidad <= 2000)));
alter table public.forest_qr_counter add constraint forest_qr_counter_id_check CHECK ((id = 1));
alter table public.forest_qr_tags add constraint forest_qr_tags_estado_check CHECK ((estado = ANY (ARRAY['disponible'::text, 'asignada'::text, 'colocada'::text, 'danada'::text, 'retirada'::text])));
alter table public.forest_species_requests add constraint forest_species_requests_estado_check CHECK ((estado = ANY (ARRAY['pendiente'::text, 'aprobada'::text, 'rechazada'::text])));
alter table public.cem_rondas add constraint cem_rondas_sin_solape EXCLUDE USING gist (daterange(desde, hasta, '[]'::text) WITH &&);
alter table public.cem_announcements add constraint cem_announcements_autor_id_fkey FOREIGN KEY (autor_id) REFERENCES cem_profiles(id);
alter table public.cem_announcements add constraint cem_announcements_cohort_id_fkey FOREIGN KEY (cohort_id) REFERENCES cem_cohorts(id) ON DELETE SET NULL;
alter table public.cem_announcements add constraint cem_announcements_course_id_fkey FOREIGN KEY (course_id) REFERENCES cem_courses(id) ON DELETE SET NULL;
alter table public.cem_aportes add constraint cem_aportes_cartera_id_fkey FOREIGN KEY (cartera_id) REFERENCES cem_carteras(id);
alter table public.cem_aportes add constraint cem_aportes_creado_por_fkey FOREIGN KEY (creado_por) REFERENCES cem_profiles(id);
alter table public.cem_aportes add constraint cem_aportes_inversor_id_fkey FOREIGN KEY (inversor_id) REFERENCES cem_inversores(id) ON DELETE RESTRICT;
alter table public.cem_appeals add constraint cem_appeals_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES cem_profiles(id) ON DELETE CASCADE;
alter table public.cem_appeals add constraint cem_appeals_resuelto_por_fkey FOREIGN KEY (resuelto_por) REFERENCES cem_profiles(id);
alter table public.cem_appeals add constraint cem_appeals_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES cem_submissions(id) ON DELETE CASCADE;
alter table public.cem_assessment_questions add constraint cem_assessment_questions_assessment_id_fkey FOREIGN KEY (assessment_id) REFERENCES cem_assessments(id) ON DELETE CASCADE;
alter table public.cem_assessment_questions add constraint cem_assessment_questions_question_id_fkey FOREIGN KEY (question_id) REFERENCES cem_questions(id) ON DELETE CASCADE;
alter table public.cem_assessments add constraint cem_assessments_course_id_fkey FOREIGN KEY (course_id) REFERENCES cem_courses(id) ON DELETE CASCADE;
alter table public.cem_assessments add constraint cem_assessments_module_id_fkey FOREIGN KEY (module_id) REFERENCES cem_modules(id) ON DELETE SET NULL;
alter table public.cem_attendance add constraint cem_attendance_class_id_fkey FOREIGN KEY (class_id) REFERENCES cem_classes(id) ON DELETE CASCADE;
alter table public.cem_attendance add constraint cem_attendance_enrollment_id_fkey FOREIGN KEY (enrollment_id) REFERENCES cem_enrollments(id) ON DELETE CASCADE;
alter table public.cem_audit_events add constraint cem_audit_events_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES cem_profiles(id);
alter table public.cem_badge_awards add constraint cem_badge_awards_badge_id_fkey FOREIGN KEY (badge_id) REFERENCES cem_badges(id) ON DELETE CASCADE;
alter table public.cem_badge_awards add constraint cem_badge_awards_otorgado_por_fkey FOREIGN KEY (otorgado_por) REFERENCES cem_profiles(id);
alter table public.cem_badge_awards add constraint cem_badge_awards_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES cem_profiles(id) ON DELETE CASCADE;
alter table public.cem_badges add constraint cem_badges_regla_curso_fkey FOREIGN KEY (regla_curso) REFERENCES cem_courses(id) ON DELETE SET NULL;
alter table public.cem_bancaribe_notificaciones add constraint cem_bancaribe_notificaciones_conciliado_por_fkey FOREIGN KEY (conciliado_por) REFERENCES cem_profiles(id) ON DELETE SET NULL;
alter table public.cem_bancaribe_notificaciones add constraint cem_bancaribe_notificaciones_enrollment_id_fkey FOREIGN KEY (enrollment_id) REFERENCES cem_enrollments(id) ON DELETE SET NULL;
alter table public.cem_bancaribe_notificaciones add constraint cem_bancaribe_notificaciones_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES cem_payments(id) ON DELETE SET NULL;
alter table public.cem_bot_borradores add constraint cem_bot_borradores_conversacion_fkey FOREIGN KEY (conversacion) REFERENCES cem_bot_conversaciones(id) ON DELETE SET NULL;
alter table public.cem_bot_borradores add constraint cem_bot_borradores_creado_por_fkey FOREIGN KEY (creado_por) REFERENCES cem_profiles(id);
alter table public.cem_bot_borradores add constraint cem_bot_borradores_resuelto_por_fkey FOREIGN KEY (resuelto_por) REFERENCES cem_profiles(id);
alter table public.cem_bot_conocimiento add constraint cem_bot_conocimiento_creado_por_fkey FOREIGN KEY (creado_por) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.cem_bot_conversaciones add constraint cem_bot_conversaciones_pausado_por_fkey FOREIGN KEY (pausado_por) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.cem_bot_conversaciones add constraint cem_bot_conversaciones_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES cem_profiles(id) ON DELETE CASCADE;
alter table public.cem_bot_escuchado add constraint cem_bot_escuchado_ficha_id_fkey FOREIGN KEY (ficha_id) REFERENCES cem_bot_conocimiento(id) ON DELETE SET NULL;
alter table public.cem_bot_mensajes add constraint cem_bot_mensajes_conversacion_id_fkey FOREIGN KEY (conversacion_id) REFERENCES cem_bot_conversaciones(id) ON DELETE CASCADE;
alter table public.cem_bot_numeros add constraint cem_bot_numeros_creado_por_fkey FOREIGN KEY (creado_por) REFERENCES cem_profiles(id);
alter table public.cem_bot_numeros add constraint cem_bot_numeros_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES cem_profiles(id) ON DELETE CASCADE;
alter table public.cem_bot_recordatorios add constraint cem_bot_recordatorios_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES cem_profiles(id) ON DELETE CASCADE;
alter table public.cem_certificates add constraint cem_certificates_anulado_por_fkey FOREIGN KEY (anulado_por) REFERENCES cem_profiles(id);
alter table public.cem_certificates add constraint cem_certificates_course_id_fkey FOREIGN KEY (course_id) REFERENCES cem_courses(id);
alter table public.cem_certificates add constraint cem_certificates_enrollment_id_fkey FOREIGN KEY (enrollment_id) REFERENCES cem_enrollments(id) ON DELETE SET NULL;
alter table public.cem_certificates add constraint cem_certificates_module_id_fkey FOREIGN KEY (module_id) REFERENCES cem_modules(id) ON DELETE SET NULL;
alter table public.cem_certificates add constraint cem_certificates_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES cem_profiles(id) ON DELETE CASCADE;
alter table public.cem_certificates add constraint cem_certificates_template_id_fkey FOREIGN KEY (template_id) REFERENCES cem_certificate_templates(id) ON DELETE SET NULL;
alter table public.cem_classes add constraint cem_classes_cohort_id_fkey FOREIGN KEY (cohort_id) REFERENCES cem_cohorts(id) ON DELETE CASCADE;
alter table public.cem_classes add constraint cem_classes_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES cem_profiles(id);
alter table public.cem_clave_pendiente add constraint cem_clave_pendiente_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES cem_profiles(id) ON DELETE CASCADE;
alter table public.cem_cohorts add constraint cem_cohorts_course_id_fkey FOREIGN KEY (course_id) REFERENCES cem_courses(id) ON DELETE CASCADE;
alter table public.cem_comentarios_guardados add constraint cem_comentarios_guardados_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES cem_profiles(id) ON DELETE CASCADE;
alter table public.cem_compras_invitado add constraint cem_compras_invitado_cohort_id_fkey FOREIGN KEY (cohort_id) REFERENCES cem_cohorts(id);
alter table public.cem_compras_invitado add constraint cem_compras_invitado_course_id_fkey FOREIGN KEY (course_id) REFERENCES cem_courses(id);
alter table public.cem_compras_invitado add constraint cem_compras_invitado_enrollment_id_fkey FOREIGN KEY (enrollment_id) REFERENCES cem_enrollments(id);
alter table public.cem_compras_invitado add constraint cem_compras_invitado_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES cem_profiles(id);
alter table public.cem_content_reviews add constraint cem_content_reviews_autor_id_fkey FOREIGN KEY (autor_id) REFERENCES cem_profiles(id);
alter table public.cem_content_reviews add constraint cem_content_reviews_course_id_fkey FOREIGN KEY (course_id) REFERENCES cem_courses(id) ON DELETE CASCADE;
alter table public.cem_content_reviews add constraint cem_content_reviews_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES cem_lessons(id) ON DELETE CASCADE;
alter table public.cem_content_reviews add constraint cem_content_reviews_revisor_id_fkey FOREIGN KEY (revisor_id) REFERENCES cem_profiles(id);
alter table public.cem_conversiones add constraint cem_conversiones_cartera_destino_fkey FOREIGN KEY (cartera_destino) REFERENCES cem_carteras(id);
alter table public.cem_conversiones add constraint cem_conversiones_cartera_origen_fkey FOREIGN KEY (cartera_origen) REFERENCES cem_carteras(id);
alter table public.cem_course_shorts add constraint cem_course_shorts_course_id_fkey FOREIGN KEY (course_id) REFERENCES cem_courses(id) ON DELETE CASCADE;
alter table public.cem_course_shorts add constraint cem_course_shorts_creado_por_fkey FOREIGN KEY (creado_por) REFERENCES cem_profiles(id) ON DELETE SET NULL;
alter table public.cem_duda_respuestas add constraint cem_duda_respuestas_autor_id_fkey FOREIGN KEY (autor_id) REFERENCES cem_profiles(id) ON DELETE CASCADE;
alter table public.cem_duda_respuestas add constraint cem_duda_respuestas_duda_id_fkey FOREIGN KEY (duda_id) REFERENCES cem_dudas(id) ON DELETE CASCADE;
alter table public.cem_dudas add constraint cem_dudas_autor_id_fkey FOREIGN KEY (autor_id) REFERENCES cem_profiles(id) ON DELETE CASCADE;
alter table public.cem_dudas add constraint cem_dudas_cohort_id_fkey FOREIGN KEY (cohort_id) REFERENCES cem_cohorts(id) ON DELETE SET NULL;
alter table public.cem_dudas add constraint cem_dudas_course_id_fkey FOREIGN KEY (course_id) REFERENCES cem_courses(id) ON DELETE CASCADE;
alter table public.cem_dudas add constraint cem_dudas_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES cem_lessons(id) ON DELETE CASCADE;
alter table public.cem_enrollments add constraint cem_enrollments_cohort_id_fkey FOREIGN KEY (cohort_id) REFERENCES cem_cohorts(id);
alter table public.cem_enrollments add constraint cem_enrollments_course_id_fkey FOREIGN KEY (course_id) REFERENCES cem_courses(id);
alter table public.cem_enrollments add constraint cem_enrollments_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES cem_profiles(id) ON DELETE CASCADE;
alter table public.cem_enrollments add constraint cem_enrollments_vendedor_id_fkey FOREIGN KEY (vendedor_id) REFERENCES cem_profiles(id);
alter table public.cem_gastos add constraint cem_gastos_cartera_id_fkey FOREIGN KEY (cartera_id) REFERENCES cem_carteras(id);
alter table public.cem_identidad add constraint cem_identidad_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES cem_profiles(id) ON DELETE CASCADE;
alter table public.cem_identidad add constraint cem_identidad_revisado_por_fkey FOREIGN KEY (revisado_por) REFERENCES cem_profiles(id);
alter table public.cem_installments add constraint cem_installments_enrollment_id_fkey FOREIGN KEY (enrollment_id) REFERENCES cem_enrollments(id) ON DELETE CASCADE;
alter table public.cem_invitaciones add constraint cem_invitaciones_cohort_id_fkey FOREIGN KEY (cohort_id) REFERENCES cem_cohorts(id) ON DELETE SET NULL;
alter table public.cem_invitaciones add constraint cem_invitaciones_course_id_fkey FOREIGN KEY (course_id) REFERENCES cem_courses(id) ON DELETE CASCADE;
alter table public.cem_invitaciones add constraint cem_invitaciones_creada_por_fkey FOREIGN KEY (creada_por) REFERENCES cem_profiles(id) ON DELETE SET NULL;
alter table public.cem_invitaciones add constraint cem_invitaciones_enrollment_id_fkey FOREIGN KEY (enrollment_id) REFERENCES cem_enrollments(id) ON DELETE SET NULL;
alter table public.cem_invitaciones add constraint cem_invitaciones_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES cem_profiles(id) ON DELETE CASCADE;
alter table public.cem_invitaciones_equipo add constraint cem_invitaciones_equipo_anulada_por_fkey FOREIGN KEY (anulada_por) REFERENCES cem_profiles(id) ON DELETE SET NULL;
alter table public.cem_invitaciones_equipo add constraint cem_invitaciones_equipo_invitada_por_fkey FOREIGN KEY (invitada_por) REFERENCES cem_profiles(id) ON DELETE SET NULL;
alter table public.cem_invitaciones_equipo add constraint cem_invitaciones_equipo_usada_por_fkey FOREIGN KEY (usada_por) REFERENCES cem_profiles(id) ON DELETE SET NULL;
alter table public.cem_lead_envios add constraint cem_lead_envios_enviado_por_fkey FOREIGN KEY (enviado_por) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.cem_lead_envios add constraint cem_lead_envios_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES cem_leads(id) ON DELETE CASCADE;
alter table public.cem_lead_envios add constraint cem_lead_envios_plantilla_id_fkey FOREIGN KEY (plantilla_id) REFERENCES cem_mensajes_plantilla(id) ON DELETE SET NULL;
alter table public.cem_leads add constraint cem_leads_atendido_por_fkey FOREIGN KEY (atendido_por) REFERENCES cem_profiles(id) ON DELETE SET NULL;
alter table public.cem_leads add constraint cem_leads_course_id_fkey FOREIGN KEY (course_id) REFERENCES cem_courses(id) ON DELETE SET NULL;
alter table public.cem_leccion_valoraciones add constraint cem_leccion_valoraciones_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES cem_lessons(id) ON DELETE CASCADE;
alter table public.cem_leccion_valoraciones add constraint cem_leccion_valoraciones_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES cem_profiles(id) ON DELETE CASCADE;
alter table public.cem_lesson_progress add constraint cem_lesson_progress_enrollment_id_fkey FOREIGN KEY (enrollment_id) REFERENCES cem_enrollments(id) ON DELETE CASCADE;
alter table public.cem_lesson_progress add constraint cem_lesson_progress_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES cem_lessons(id) ON DELETE CASCADE;
alter table public.cem_lessons add constraint cem_lessons_module_id_fkey FOREIGN KEY (module_id) REFERENCES cem_modules(id) ON DELETE CASCADE;
alter table public.cem_liquidaciones add constraint cem_liquidaciones_cartera_id_fkey FOREIGN KEY (cartera_id) REFERENCES cem_carteras(id);
alter table public.cem_liquidaciones add constraint cem_liquidaciones_creado_por_fkey FOREIGN KEY (creado_por) REFERENCES cem_profiles(id);
alter table public.cem_liquidaciones add constraint cem_liquidaciones_eliminado_por_fkey FOREIGN KEY (eliminado_por) REFERENCES cem_profiles(id);
alter table public.cem_liquidaciones add constraint cem_liquidaciones_inversor_id_fkey FOREIGN KEY (inversor_id) REFERENCES cem_inversores(id) ON DELETE RESTRICT;
alter table public.cem_liquidaciones add constraint cem_liquidaciones_ronda_id_fkey FOREIGN KEY (ronda_id) REFERENCES cem_rondas(id) ON DELETE RESTRICT;
alter table public.cem_media add constraint cem_media_course_id_fkey FOREIGN KEY (course_id) REFERENCES cem_courses(id) ON DELETE SET NULL;
alter table public.cem_media add constraint cem_media_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES cem_lessons(id) ON DELETE SET NULL;
alter table public.cem_media add constraint cem_media_module_id_fkey FOREIGN KEY (module_id) REFERENCES cem_modules(id) ON DELETE SET NULL;
alter table public.cem_media add constraint cem_media_subido_por_fkey FOREIGN KEY (subido_por) REFERENCES cem_profiles(id);
alter table public.cem_mensajes_plantilla add constraint cem_mensajes_plantilla_creada_por_fkey FOREIGN KEY (creada_por) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.cem_metodos_pago add constraint cem_metodos_pago_cartera_id_fkey FOREIGN KEY (cartera_id) REFERENCES cem_carteras(id);
alter table public.cem_modules add constraint cem_modules_course_id_fkey FOREIGN KEY (course_id) REFERENCES cem_courses(id) ON DELETE CASCADE;
alter table public.cem_modules add constraint cem_modules_profesor_id_fkey FOREIGN KEY (profesor_id) REFERENCES cem_profiles(id) ON DELETE SET NULL;
alter table public.cem_muro add constraint cem_muro_assessment_id_fkey FOREIGN KEY (assessment_id) REFERENCES cem_assessments(id) ON DELETE SET NULL;
alter table public.cem_muro add constraint cem_muro_autor_id_fkey FOREIGN KEY (autor_id) REFERENCES cem_profiles(id);
alter table public.cem_muro add constraint cem_muro_cohort_id_fkey FOREIGN KEY (cohort_id) REFERENCES cem_cohorts(id) ON DELETE CASCADE;
alter table public.cem_muro add constraint cem_muro_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES cem_lessons(id) ON DELETE SET NULL;
alter table public.cem_muro_comentarios add constraint cem_muro_comentarios_autor_id_fkey FOREIGN KEY (autor_id) REFERENCES cem_profiles(id);
alter table public.cem_muro_comentarios add constraint cem_muro_comentarios_post_id_fkey FOREIGN KEY (post_id) REFERENCES cem_muro(id) ON DELETE CASCADE;
alter table public.cem_notificaciones add constraint cem_notificaciones_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES cem_profiles(id) ON DELETE CASCADE;
alter table public.cem_payments add constraint cem_payments_cartera_id_fkey FOREIGN KEY (cartera_id) REFERENCES cem_carteras(id);
alter table public.cem_payments add constraint cem_payments_enrollment_id_fkey FOREIGN KEY (enrollment_id) REFERENCES cem_enrollments(id) ON DELETE CASCADE;
alter table public.cem_payments add constraint cem_payments_installment_id_fkey FOREIGN KEY (installment_id) REFERENCES cem_installments(id) ON DELETE SET NULL;
alter table public.cem_payments add constraint cem_payments_registrado_por_fkey FOREIGN KEY (registrado_por) REFERENCES cem_profiles(id);
alter table public.cem_plantillas_mensaje add constraint cem_plantillas_mensaje_creada_por_fkey FOREIGN KEY (creada_por) REFERENCES cem_profiles(id) ON DELETE SET NULL;
alter table public.cem_portafolio add constraint cem_portafolio_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES cem_profiles(id) ON DELETE CASCADE;
alter table public.cem_profiles add constraint cem_profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.cem_questions add constraint cem_questions_course_id_fkey FOREIGN KEY (course_id) REFERENCES cem_courses(id) ON DELETE SET NULL;
alter table public.cem_questions add constraint cem_questions_module_id_fkey FOREIGN KEY (module_id) REFERENCES cem_modules(id) ON DELETE SET NULL;
alter table public.cem_recurso_entregas add constraint cem_recurso_entregas_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES cem_leads(id) ON DELETE SET NULL;
alter table public.cem_recurso_entregas add constraint cem_recurso_entregas_recurso_id_fkey FOREIGN KEY (recurso_id) REFERENCES cem_recursos(id) ON DELETE CASCADE;
alter table public.cem_recursos add constraint cem_recursos_creado_por_fkey FOREIGN KEY (creado_por) REFERENCES cem_profiles(id) ON DELETE SET NULL;
alter table public.cem_reproducciones add constraint cem_reproducciones_course_id_fkey FOREIGN KEY (course_id) REFERENCES cem_courses(id) ON DELETE SET NULL;
alter table public.cem_reproducciones add constraint cem_reproducciones_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES cem_lessons(id) ON DELETE CASCADE;
alter table public.cem_reproducciones add constraint cem_reproducciones_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES cem_profiles(id) ON DELETE CASCADE;
alter table public.cem_ronda_partes add constraint cem_ronda_partes_inversor_id_fkey FOREIGN KEY (inversor_id) REFERENCES cem_inversores(id) ON DELETE RESTRICT;
alter table public.cem_ronda_partes add constraint cem_ronda_partes_ronda_id_fkey FOREIGN KEY (ronda_id) REFERENCES cem_rondas(id) ON DELETE CASCADE;
alter table public.cem_solicitudes_inscripcion add constraint cem_solicitudes_inscripcion_enrollment_id_fkey FOREIGN KEY (enrollment_id) REFERENCES cem_enrollments(id) ON DELETE CASCADE;
alter table public.cem_solicitudes_inscripcion add constraint cem_solicitudes_inscripcion_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES cem_profiles(id) ON DELETE CASCADE;
alter table public.cem_solicitudes_inscripcion add constraint cem_solicitudes_inscripcion_resuelto_por_fkey FOREIGN KEY (resuelto_por) REFERENCES cem_profiles(id);
alter table public.cem_solicitudes_perfil add constraint cem_solicitudes_perfil_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES cem_profiles(id) ON DELETE CASCADE;
alter table public.cem_solicitudes_perfil add constraint cem_solicitudes_perfil_resuelto_por_fkey FOREIGN KEY (resuelto_por) REFERENCES cem_profiles(id);
alter table public.cem_stripe_sesiones add constraint cem_stripe_sesiones_installment_id_fkey FOREIGN KEY (installment_id) REFERENCES cem_installments(id) ON DELETE CASCADE;
alter table public.cem_stripe_sesiones add constraint cem_stripe_sesiones_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES cem_profiles(id) ON DELETE CASCADE;
alter table public.cem_submissions add constraint cem_submissions_assessment_id_fkey FOREIGN KEY (assessment_id) REFERENCES cem_assessments(id) ON DELETE CASCADE;
alter table public.cem_submissions add constraint cem_submissions_calificado_por_fkey FOREIGN KEY (calificado_por) REFERENCES cem_profiles(id);
alter table public.cem_submissions add constraint cem_submissions_enrollment_id_fkey FOREIGN KEY (enrollment_id) REFERENCES cem_enrollments(id) ON DELETE CASCADE;
alter table public.cem_teacher_assignments add constraint cem_teacher_assignments_cohort_id_fkey FOREIGN KEY (cohort_id) REFERENCES cem_cohorts(id) ON DELETE CASCADE;
alter table public.cem_teacher_assignments add constraint cem_teacher_assignments_course_id_fkey FOREIGN KEY (course_id) REFERENCES cem_courses(id) ON DELETE CASCADE;
alter table public.cem_teacher_assignments add constraint cem_teacher_assignments_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES cem_profiles(id) ON DELETE CASCADE;
alter table public.cem_ticket_messages add constraint cem_ticket_messages_autor_id_fkey FOREIGN KEY (autor_id) REFERENCES cem_profiles(id);
alter table public.cem_ticket_messages add constraint cem_ticket_messages_ticket_id_fkey FOREIGN KEY (ticket_id) REFERENCES cem_tickets(id) ON DELETE CASCADE;
alter table public.cem_tickets add constraint cem_tickets_asignado_a_fkey FOREIGN KEY (asignado_a) REFERENCES cem_profiles(id);
alter table public.cem_tickets add constraint cem_tickets_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES cem_profiles(id) ON DELETE CASCADE;
alter table public.cem_valoraciones add constraint cem_valoraciones_class_id_fkey FOREIGN KEY (class_id) REFERENCES cem_classes(id) ON DELETE CASCADE;
alter table public.cem_valoraciones add constraint cem_valoraciones_cohort_id_fkey FOREIGN KEY (cohort_id) REFERENCES cem_cohorts(id) ON DELETE CASCADE;
alter table public.cem_valoraciones add constraint cem_valoraciones_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES cem_profiles(id) ON DELETE CASCADE;
alter table public.cem_wa_salientes add constraint cem_wa_salientes_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES cem_profiles(id) ON DELETE SET NULL;
alter table public.cert_carpetas add constraint cert_carpetas_creada_por_fkey FOREIGN KEY (creada_por) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.cert_certificates add constraint cert_certificates_reemplaza_a_fkey FOREIGN KEY (reemplaza_a) REFERENCES cert_certificates(id);
alter table public.forest_ai_predictions add constraint forest_ai_predictions_tree_id_fkey FOREIGN KEY (tree_id) REFERENCES forest_trees(id) ON DELETE CASCADE;
alter table public.forest_audit_events add constraint forest_audit_events_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES forest_profiles(id);
alter table public.forest_audit_events add constraint forest_audit_events_tree_id_fkey FOREIGN KEY (tree_id) REFERENCES forest_trees(id) ON DELETE SET NULL;
alter table public.forest_code_sequences add constraint forest_code_sequences_project_id_fkey FOREIGN KEY (project_id) REFERENCES forest_projects(id);
alter table public.forest_profiles add constraint forest_profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.forest_public_content add constraint forest_public_content_actualizado_por_fkey FOREIGN KEY (actualizado_por) REFERENCES forest_profiles(id);
alter table public.forest_public_content add constraint forest_public_content_tree_id_fkey FOREIGN KEY (tree_id) REFERENCES forest_trees(id) ON DELETE CASCADE;
alter table public.forest_public_templates add constraint forest_public_templates_actualizado_por_fkey FOREIGN KEY (actualizado_por) REFERENCES forest_profiles(id);
alter table public.forest_push_subscriptions add constraint forest_push_subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES forest_profiles(id);
alter table public.forest_qr_batches add constraint forest_qr_batches_creado_por_fkey FOREIGN KEY (creado_por) REFERENCES forest_profiles(id);
alter table public.forest_qr_tags add constraint forest_qr_tags_asignada_por_fkey FOREIGN KEY (asignada_por) REFERENCES forest_profiles(id);
alter table public.forest_qr_tags add constraint forest_qr_tags_batch_id_fkey FOREIGN KEY (batch_id) REFERENCES forest_qr_batches(id);
alter table public.forest_qr_tags add constraint forest_qr_tags_reemplaza_a_fkey FOREIGN KEY (reemplaza_a) REFERENCES forest_qr_tags(id);
alter table public.forest_qr_tags add constraint forest_qr_tags_tree_id_fkey FOREIGN KEY (tree_id) REFERENCES forest_trees(id);
alter table public.forest_reviews add constraint forest_reviews_supervisor_id_fkey FOREIGN KEY (supervisor_id) REFERENCES forest_profiles(id);
alter table public.forest_reviews add constraint forest_reviews_tree_id_fkey FOREIGN KEY (tree_id) REFERENCES forest_trees(id) ON DELETE CASCADE;
alter table public.forest_species_requests add constraint forest_species_requests_especie_creada_id_fkey FOREIGN KEY (especie_creada_id) REFERENCES forest_species_catalog(id);
alter table public.forest_species_requests add constraint forest_species_requests_resuelto_por_fkey FOREIGN KEY (resuelto_por) REFERENCES forest_profiles(id);
alter table public.forest_species_requests add constraint forest_species_requests_supervisor_id_fkey FOREIGN KEY (supervisor_id) REFERENCES forest_profiles(id);
alter table public.forest_species_requests add constraint forest_species_requests_tree_id_fkey FOREIGN KEY (tree_id) REFERENCES forest_trees(id);
alter table public.forest_tree_photos add constraint forest_tree_photos_tree_id_fkey FOREIGN KEY (tree_id) REFERENCES forest_trees(id) ON DELETE CASCADE;
alter table public.forest_trees add constraint forest_trees_asignado_a_fkey FOREIGN KEY (asignado_a) REFERENCES forest_profiles(id);
alter table public.forest_trees add constraint forest_trees_especie_confirmada_id_fkey FOREIGN KEY (especie_confirmada_id) REFERENCES forest_species_catalog(id);
alter table public.forest_trees add constraint forest_trees_project_id_fkey FOREIGN KEY (project_id) REFERENCES forest_projects(id);
alter table public.forest_trees add constraint forest_trees_registrador_id_fkey FOREIGN KEY (registrador_id) REFERENCES forest_profiles(id);
alter table public.pm_project_events add constraint pm_project_events_project_id_fkey FOREIGN KEY (project_id) REFERENCES pm_projects(id);
alter table public.quote_events add constraint quote_events_quote_id_fkey FOREIGN KEY (quote_id) REFERENCES quotes(id) ON DELETE CASCADE;
