-- Índices
-- ═══════════════════════════════════════════════════════════════════════════
-- Generado por herramientas/volcar-esquema.sql. NO se edita a mano: se
-- vuelve a generar y se perdería lo escrito. Los cambios se hacen en la
-- base y luego se regenera esto.

create index if not exists cem_announcements_autor_idx ON public.cem_announcements USING btree (autor_id);
create index if not exists cem_announcements_cohort_idx ON public.cem_announcements USING btree (cohort_id);
create index if not exists cem_announcements_course_idx ON public.cem_announcements USING btree (course_id);
create index if not exists cem_aportes_inversor ON public.cem_aportes USING btree (inversor_id) WHERE (NOT eliminado);
create index if not exists cem_appeals_profile_idx ON public.cem_appeals USING btree (profile_id);
create index if not exists cem_appeals_resuelto_idx ON public.cem_appeals USING btree (resuelto_por);
create index if not exists cem_appeals_submission_idx ON public.cem_appeals USING btree (submission_id);
create index if not exists cem_aq_question_idx ON public.cem_assessment_questions USING btree (question_id);
create index if not exists cem_assess_course_idx ON public.cem_assessments USING btree (course_id);
create index if not exists cem_assessments_module_idx ON public.cem_assessments USING btree (module_id);
create index if not exists cem_attendance_enrollment_idx ON public.cem_attendance USING btree (enrollment_id);
create index if not exists cem_audit_actor_idx ON public.cem_audit_events USING btree (actor_id);
create index if not exists cem_audit_created_idx ON public.cem_audit_events USING btree (created_at DESC);
create index if not exists cem_badge_awards_otorgado_idx ON public.cem_badge_awards USING btree (otorgado_por);
create index if not exists cem_badge_awards_profile_idx ON public.cem_badge_awards USING btree (profile_id);
create index if not exists cem_banc_notif_conciliado_idx ON public.cem_bancaribe_notificaciones USING btree (conciliado_por);
create index if not exists cem_banc_notif_enrollment_idx ON public.cem_bancaribe_notificaciones USING btree (enrollment_id);
create index if not exists cem_banc_notif_payment_idx ON public.cem_bancaribe_notificaciones USING btree (payment_id);
create index if not exists cem_bancaribe_notif_debtor ON public.cem_bancaribe_notificaciones USING btree (debtor_id);
create index if not exists cem_bancaribe_notif_estado ON public.cem_bancaribe_notificaciones USING btree (estado, recibido_en DESC);
create unique index if not exists cem_bancaribe_notif_ref_uniq ON public.cem_bancaribe_notificaciones USING btree (origin_bank_code, origin_bank_reference, amount) WHERE (origin_bank_reference IS NOT NULL);
create index if not exists cem_bot_borradores_pendientes ON public.cem_bot_borradores USING btree (creado_por, estado, created_at DESC);
create index if not exists cem_bot_conocimiento_ambito ON public.cem_bot_conocimiento USING btree (ambito) WHERE activo;
create index if not exists cem_bot_conv_escaladas ON public.cem_bot_conversaciones USING btree (escalado_en DESC) WHERE (escalado_en IS NOT NULL);
create index if not exists cem_bot_conv_huella_idx ON public.cem_bot_conversaciones USING btree (huella, created_at DESC) WHERE (huella IS NOT NULL);
create index if not exists cem_bot_conv_persona ON public.cem_bot_conversaciones USING btree (profile_id, ultimo_en DESC);
create index if not exists cem_bot_escuchado_fecha ON public.cem_bot_escuchado USING btree (created_at DESC);
create index if not exists cem_bot_msj_conv ON public.cem_bot_mensajes USING btree (conversacion_id, created_at);
create index if not exists cem_certificates_course_idx ON public.cem_certificates USING btree (course_id);
create index if not exists cem_certificates_enrollment_idx ON public.cem_certificates USING btree (enrollment_id);
create index if not exists cem_certificates_profile_idx ON public.cem_certificates USING btree (profile_id);
create index if not exists cem_certificates_template_idx ON public.cem_certificates USING btree (template_id);
create unique index if not exists cem_certificates_un_modulo_por_inscripcion ON public.cem_certificates USING btree (enrollment_id, module_id) WHERE ((module_id IS NOT NULL) AND (anulado_en IS NULL));
create index if not exists cem_classes_cohort_idx ON public.cem_classes USING btree (cohort_id);
create index if not exists cem_classes_fecha_idx ON public.cem_classes USING btree (fecha);
create index if not exists cem_classes_teacher_idx ON public.cem_classes USING btree (teacher_id);
create index if not exists cem_cohorts_course_idx ON public.cem_cohorts USING btree (course_id);
create index if not exists cem_comentarios_guardados_idx ON public.cem_comentarios_guardados USING btree (profile_id, usos DESC);
create index if not exists cem_compras_invitado_email_idx ON public.cem_compras_invitado USING btree (lower(email), creada_en DESC);
create index if not exists cem_content_reviews_autor_idx ON public.cem_content_reviews USING btree (autor_id);
create index if not exists cem_content_reviews_course_idx ON public.cem_content_reviews USING btree (course_id);
create index if not exists cem_content_reviews_lesson_idx ON public.cem_content_reviews USING btree (lesson_id);
create index if not exists cem_content_reviews_revisor_idx ON public.cem_content_reviews USING btree (revisor_id);
create index if not exists cem_conversiones_fecha ON public.cem_conversiones USING btree (fecha DESC) WHERE (NOT eliminado);
create index if not exists cem_correo_cola_pendientes_idx ON public.cem_correo_cola USING btree (estado, created_at) WHERE (estado = 'pendiente'::text);
create index if not exists cem_correo_cola_por_despachar ON public.cem_correo_cola USING btree (proximo_intento_en) WHERE (estado = 'pendiente'::text);
create index if not exists cem_correo_cola_por_recoger ON public.cem_correo_cola USING btree (request_id) WHERE (estado = 'enviando'::text);
create unique index if not exists cem_correo_cola_sin_repetir ON public.cem_correo_cola USING btree (clave) WHERE (estado = 'pendiente'::text);
create index if not exists cem_course_shorts_por_curso ON public.cem_course_shorts USING btree (course_id, orden);
create index if not exists cem_duda_respuestas_idx ON public.cem_duda_respuestas USING btree (duda_id, created_at);
create index if not exists cem_dudas_curso_idx ON public.cem_dudas USING btree (course_id) WHERE ((NOT resuelta) AND (NOT eliminada));
create index if not exists cem_dudas_leccion_idx ON public.cem_dudas USING btree (lesson_id, created_at DESC);
create index if not exists cem_enroll_cohort_idx ON public.cem_enrollments USING btree (cohort_id);
create index if not exists cem_enroll_profile_idx ON public.cem_enrollments USING btree (profile_id);
create index if not exists cem_enrollments_course_idx ON public.cem_enrollments USING btree (course_id);
create index if not exists cem_enrollments_vendedor_idx ON public.cem_enrollments USING btree (vendedor_id);
create index if not exists cem_gastos_fecha ON public.cem_gastos USING btree (fecha DESC) WHERE (NOT eliminado);
create index if not exists cem_gastos_linea ON public.cem_gastos USING btree (linea) WHERE (NOT COALESCE(eliminado, false));
create index if not exists cem_inst_enroll_idx ON public.cem_installments USING btree (enrollment_id);
create index if not exists cem_installments_estado_venc_idx ON public.cem_installments USING btree (estado, fecha_vencimiento);
create index if not exists cem_invitaciones_por_persona ON public.cem_invitaciones USING btree (profile_id, estado);
create unique index if not exists cem_invitaciones_una_viva ON public.cem_invitaciones USING btree (profile_id, course_id) WHERE (estado = 'pendiente'::text);
create index if not exists cem_inv_eq_email ON public.cem_invitaciones_equipo USING btree (lower(email));
create index if not exists cem_inv_eq_estado ON public.cem_invitaciones_equipo USING btree (usada_en, anulada_en, vence_en);
create index if not exists cem_lead_envios_por_lead ON public.cem_lead_envios USING btree (lead_id);
create index if not exists cem_lead_envios_por_plantilla ON public.cem_lead_envios USING btree (plantilla_clave, lead_id);
create index if not exists cem_leads_curso_idx ON public.cem_leads USING btree (course_id);
create index if not exists cem_leads_estado_idx ON public.cem_leads USING btree (estado, created_at DESC);
create unique index if not exists cem_leads_un_correo_una_persona ON public.cem_leads USING btree (lower(TRIM(BOTH FROM email))) WHERE (COALESCE(TRIM(BOTH FROM email), ''::text) <> ''::text);
create index if not exists cem_leccion_valoraciones_por_leccion ON public.cem_leccion_valoraciones USING btree (lesson_id);
create index if not exists cem_lesson_progress_lesson_idx ON public.cem_lesson_progress USING btree (lesson_id);
create index if not exists cem_lessons_module_idx ON public.cem_lessons USING btree (module_id);
create index if not exists cem_liquidaciones_lote ON public.cem_liquidaciones USING btree (lote);
create index if not exists cem_liquidaciones_reparto ON public.cem_liquidaciones USING btree (ronda_id, inversor_id, linea) WHERE (NOT eliminado);
create index if not exists cem_media_course_idx ON public.cem_media USING btree (course_id);
create index if not exists cem_media_lesson_idx ON public.cem_media USING btree (lesson_id);
create index if not exists cem_media_module_idx ON public.cem_media USING btree (module_id);
create index if not exists cem_media_subido_idx ON public.cem_media USING btree (subido_por);
create index if not exists cem_modules_course_idx ON public.cem_modules USING btree (course_id);
create index if not exists cem_modules_profesor_idx ON public.cem_modules USING btree (profesor_id) WHERE (profesor_id IS NOT NULL);
create index if not exists cem_muro_cohorte ON public.cem_muro USING btree (cohort_id, created_at DESC) WHERE (NOT eliminado);
create index if not exists cem_muro_com_post ON public.cem_muro_comentarios USING btree (post_id, created_at) WHERE (NOT eliminado);
create index if not exists cem_notificaciones_perfil_idx ON public.cem_notificaciones USING btree (profile_id, leida_en NULLS FIRST, created_at DESC);
create index if not exists cem_pay_enroll_idx ON public.cem_payments USING btree (enrollment_id);
create index if not exists cem_payments_cartera ON public.cem_payments USING btree (cartera_id) WHERE (estado = 'confirmado'::text);
create index if not exists cem_payments_estado_fecha_idx ON public.cem_payments USING btree (estado, fecha DESC);
create index if not exists cem_payments_installment_idx ON public.cem_payments USING btree (installment_id);
create index if not exists cem_payments_referencia_idx ON public.cem_payments USING btree (referencia);
create index if not exists cem_payments_registrado_idx ON public.cem_payments USING btree (registrado_por);
create index if not exists cem_plantillas_mensaje_usos_idx ON public.cem_plantillas_mensaje USING btree (usos DESC, nombre);
create index if not exists cem_portafolio_por_persona ON public.cem_portafolio USING btree (profile_id, orden);
create unique index if not exists cem_profiles_perfil_slug_key ON public.cem_profiles USING btree (perfil_slug) WHERE (perfil_slug IS NOT NULL);
create index if not exists cem_profiles_rol_idx ON public.cem_profiles USING btree (rol);
create index if not exists cem_questions_course_idx ON public.cem_questions USING btree (course_id);
create index if not exists cem_questions_modulo ON public.cem_questions USING btree (module_id);
create index if not exists cem_entregas_por_recurso ON public.cem_recurso_entregas USING btree (recurso_id, created_at DESC);
create unique index if not exists cem_recurso_entregas_una_por_persona ON public.cem_recurso_entregas USING btree (recurso_id, email);
create index if not exists cem_reproducciones_por_leccion ON public.cem_reproducciones USING btree (lesson_id, ultimo_en DESC);
create index if not exists cem_reproducciones_por_persona ON public.cem_reproducciones USING btree (profile_id, ultimo_en DESC);
create unique index if not exists cem_reproducciones_una_por_dia ON public.cem_reproducciones USING btree (profile_id, lesson_id, dia);
create index if not exists cem_ronda_partes_ronda ON public.cem_ronda_partes USING btree (ronda_id);
create index if not exists cem_solicitudes_insc_estado_idx ON public.cem_solicitudes_inscripcion USING btree (estado, created_at DESC);
create index if not exists cem_solicitudes_insc_perfil_idx ON public.cem_solicitudes_inscripcion USING btree (profile_id);
create index if not exists cem_solicitudes_inscripcion_enrollment_idx ON public.cem_solicitudes_inscripcion USING btree (enrollment_id);
create index if not exists cem_solicitudes_inscripcion_resuelto_por_idx ON public.cem_solicitudes_inscripcion USING btree (resuelto_por);
create index if not exists cem_solicitudes_perfil_estado_idx ON public.cem_solicitudes_perfil USING btree (estado, created_at DESC);
create index if not exists cem_solicitudes_perfil_perfil_idx ON public.cem_solicitudes_perfil USING btree (profile_id);
create index if not exists cem_solicitudes_perfil_resuelto_por_idx ON public.cem_solicitudes_perfil USING btree (resuelto_por);
create index if not exists cem_stripe_sesiones_por_cuota ON public.cem_stripe_sesiones USING btree (installment_id, created_at DESC);
create index if not exists cem_sub_assess_idx ON public.cem_submissions USING btree (assessment_id);
create index if not exists cem_sub_enroll_idx ON public.cem_submissions USING btree (enrollment_id);
create index if not exists cem_submissions_assess_enroll_idx ON public.cem_submissions USING btree (assessment_id, enrollment_id);
create index if not exists cem_submissions_calificado_idx ON public.cem_submissions USING btree (calificado_por);
create index if not exists cem_tasa_peticiones_abiertas ON public.cem_tasa_peticiones USING btree (estado) WHERE (estado = 'pidiendo'::text);
create unique index if not exists cem_tasas_bcv_moneda_fecha ON public.cem_tasas_bcv USING btree (moneda, fecha, id_tasa);
create unique index if not exists cem_tasas_bcv_moneda_fecha_idtasa ON public.cem_tasas_bcv USING btree (moneda, fecha, id_tasa);
create index if not exists cem_teacher_assign_cohort_idx ON public.cem_teacher_assignments USING btree (cohort_id);
create index if not exists cem_teacher_assign_course_idx ON public.cem_teacher_assignments USING btree (course_id);
create index if not exists cem_teacher_assign_teacher_idx ON public.cem_teacher_assignments USING btree (teacher_id);
create index if not exists cem_ticket_messages_autor_idx ON public.cem_ticket_messages USING btree (autor_id);
create index if not exists cem_ticket_messages_ticket_idx ON public.cem_ticket_messages USING btree (ticket_id);
create index if not exists cem_tickets_asignado_idx ON public.cem_tickets USING btree (asignado_a);
create index if not exists cem_tickets_profile_idx ON public.cem_tickets USING btree (profile_id);
create index if not exists cem_valoraciones_cohorte ON public.cem_valoraciones USING btree (cohort_id);
create index if not exists cem_wa_salientes_pendientes ON public.cem_wa_salientes USING btree (creado_en) WHERE (estado = 'pendiente'::text);
create unique index if not exists cem_wa_salientes_una_vez ON public.cem_wa_salientes USING btree (telefono, motivo, entidad_id) WHERE (entidad_id IS NOT NULL);
create index if not exists cert_certificates_reemplaza_a_idx ON public.cert_certificates USING btree (reemplaza_a);
create index if not exists forest_ai_predictions_tree_id_idx ON public.forest_ai_predictions USING btree (tree_id);
create index if not exists forest_audit_events_tree_id_idx ON public.forest_audit_events USING btree (tree_id);
create index if not exists forest_qr_tags_estado ON public.forest_qr_tags USING btree (estado);
create unique index if not exists forest_qr_tags_tree_activa ON public.forest_qr_tags USING btree (tree_id) WHERE ((tree_id IS NOT NULL) AND (estado = ANY (ARRAY['asignada'::text, 'colocada'::text])));
create index if not exists forest_reviews_tree_id_idx ON public.forest_reviews USING btree (tree_id);
create index if not exists forest_tree_photos_tree_id_idx ON public.forest_tree_photos USING btree (tree_id);
create unique index if not exists forest_trees_client_id_key ON public.forest_trees USING btree (client_id) WHERE (client_id IS NOT NULL);
create index if not exists forest_trees_estado_idx ON public.forest_trees USING btree (estado);
create index if not exists forest_trees_registrador_id_idx ON public.forest_trees USING btree (registrador_id);
create index if not exists quote_events_quote_id_idx ON public.quote_events USING btree (quote_id, created_at);
